
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osciugvldgdwbihrkxrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zY2l1Z3ZsZGdkd2JpaHJreHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDI0NDIsImV4cCI6MjA1NzYxODQ0Mn0.ecVOtdcT3pwIRR6uIKTX92O-ARzycM8k3eBWaUAFgP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
